name: Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: [self-hosted, Linux, X64]
    environment: docker
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check directory structure
        run: |
          pwd
          ls -la
          if [ -d "./Capstone" ]; then
            echo "Capstone directory exists"
            ls -la ./Capstone
          else
            echo "Capstone directory does not exist"
            ls -la
            exit 1
          fi

      - name: Check Docker status
        run: |
          docker --version
          docker ps
          docker info

      - name: Run docker compose
        working-directory: ./Capstone
        run: |
          # Try new syntax first
          if docker compose version &>/dev/null; then
            echo "Using docker compose (new syntax)"
            docker compose up --build -d
          else
            echo "Using docker-compose (old syntax)"
            docker-compose up --build -d
          fi

      - name: Verify containers are running
        working-directory: ./Capstone
        run: |
          sleep 10
          docker ps
          echo "Deployment completed successfully"

      - name: Run automated tests
        run: |
          # Determine which docker compose command to use
          if docker compose version &>/dev/null; then
            DOCKER_COMPOSE_CMD="docker compose"
          else
            DOCKER_COMPOSE_CMD="docker-compose"
          fi
          
          # Find the correct container name
          CONTAINER_NAME=$(docker ps --format '{{.Names}}' | grep 'capstone-server')
          
          if [ -z "$CONTAINER_NAME" ]; then
            echo "❌ Capstone server container not found!"
            docker ps
            exit 1
          fi
          
          echo "Found container: $CONTAINER_NAME"
          
          # Run the tests in the appropriate container
          echo "Running automated tests..."
          docker exec -T $CONTAINER_NAME dotnet test ../Capstone.HPTY.Test/Capstone.HPTY.Test.csproj
          
          # Check if tests passed
          if [ $? -eq 0 ]; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Tests failed!"
            exit 1
          fi
