name: Deployment

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: [self-hosted, Linux, X64]
    environment: docker
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check directory structure
        run: |
          pwd
          ls -la
          if [ -d "./Capstone" ]; then
            echo "Capstone directory exists"
            ls -la ./Capstone
          else
            echo "Capstone directory does not exist"
            ls -la
            exit 1
          fi

      - name: Check Docker status
        run: |
          docker --version
          docker ps
          docker info

      - name: Run docker compose
        working-directory: ./Capstone
        run: |
          # Try new syntax first
          if docker compose version &>/dev/null; then
            echo "Using docker compose (new syntax)"
            docker compose up --build -d
          else
            echo "Using docker-compose (old syntax)"
            docker-compose up --build -d
          fi

      - name: Verify containers are running
        working-directory: ./Capstone
        run: |
          sleep 10
          docker ps
          echo "Deployment completed successfully"

      - name: Verify containers and run tests
        run: |
          # Determine which docker compose command to use
          if docker compose version &>/dev/null; then
            DOCKER_COMPOSE_CMD="docker compose"
          else
            DOCKER_COMPOSE_CMD="docker-compose"
          fi
          
          # List all running containers
          echo "Listing all running containers:"
          docker ps
          
          # Check if the api container is running
          if ! docker ps --format '{{.Names}}' | grep -q "api"; then
            echo "❌ API container is not running! Checking logs..."
            cd ./Capstone
            $DOCKER_COMPOSE_CMD logs
            
            echo "Attempting to restart the container..."
            $DOCKER_COMPOSE_CMD up -d
            cd ..
            
            sleep 10
            
            if ! docker ps --format '{{.Names}}' | grep -q "api"; then
              echo "❌ Failed to start API container after retry!"
              exit 1
            fi
          fi
          
          # Run the tests directly on the runner (not in the container)
          echo "Running automated tests..."
          dotnet test ./Capstone.HPTY.Test/Capstone.HPTY.Test.csproj
          
          # Check if tests passed
          if [ $? -eq 0 ]; then
            echo "✅ All tests passed successfully!"
          else
            echo "❌ Tests failed!"
            exit 1
          fi
