name: Deployment

on:
  push:
    branches:
      - main
    
jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker     
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Run `docker compose`
      working-directory: ./Capstone
      run: docker compose up --build -d
